BazyDanychProjekt/Controllers/AdminPanelController.cs
using BazyDanychProjekt.Data;
using BazyDanychProjekt.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BazyDanychProjekt.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminPanelController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdminPanelController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var hotele = await _context.Hotele.ToListAsync();
            return View(hotele);
        }

        [HttpPost]
        public async Task<IActionResult> DodajHotel(DodajHotelViewModel model)
        {
            var hotel = new Hotel
            {
                Nazwa = model.Nazwa,
                Kraj = model.Kraj,
                Miasto = model.Miasto,
                Gwiazdki = model.Gwiazdki,
                Opis = model.Opis
            };
            _context.Hotele.Add(hotel);
            await _context.SaveChangesAsync();

            int dodanyHotelId = hotel.Id;

            var zdjecie = new Zdjecie
            {
                HotelId = dodanyHotelId,
                Url = model.url
            };
            _context.Zdjecia.Add(zdjecie);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> EdytujHotel(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hotel = await _context.Hotele
                .Include(h => h.Zdjecia)
                .Include(h => h.Pokoje)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (hotel == null)
            {
                return NotFound();
            }

            return View(hotel);
        }

        [HttpPost]
        public async Task<IActionResult> EdytujHotel(int id, Hotel hotel)
        {
            if (id != hotel.Id)
            {
                return NotFound();
            }

                try
                {
                    _context.Entry(hotel).State = EntityState.Modified;
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HotelExists(hotel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> EdytujZdjeciaHotelu(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hotel = await _context.Hotele
                .Include(h => h.Zdjecia)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (hotel == null)
            {
                return NotFound();
            }

            return View(hotel);
        }

        [HttpPost]
        public async Task<IActionResult> EdytujZdjeciaHotelu(int hotelId, string url)
        {
            var hotel = await _context.Hotele.Include(h => h.Zdjecia).FirstOrDefaultAsync(h => h.Id == hotelId);
            if (hotel == null)
            {
                return NotFound();
            }

            var noweZdjecie = new Zdjecie { Url = url };
            hotel.Zdjecia.Add(noweZdjecie);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(EdytujZdjeciaHotelu), new { id = hotelId });
        }

        public async Task<IActionResult> UsunZdjecie(int? zdjecieId)
        {
            if (zdjecieId == null)
            {
                return NotFound();
            }

            var zdjecie = await _context.Zdjecia.FindAsync(zdjecieId);
            if (zdjecie == null)
            {
                return NotFound();
            }

            ViewData["idHotelu"] = zdjecie.HotelId;

            return View(zdjecie);
        }

        [HttpPost]
        public async Task<IActionResult> PotwierdzUsuniecieZdjecia(int zdjecieId, int idHotelu)
        {
            var zdjecie = await _context.Zdjecia.FindAsync(zdjecieId);
            if (zdjecie == null)
            {
                return NotFound();
            }

            _context.Zdjecia.Remove(zdjecie);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(EdytujZdjeciaHotelu), new { id = idHotelu });
        }

        public async Task<IActionResult> UsunHotel(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hotel = await _context.Hotele
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hotel == null)
            {
                return NotFound();
            }

            return View(hotel);
        }

        [HttpPost, ActionName("UsunHotel")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PotwierdzUsuniecieHotelu(int id)
        {
            var hotel = await _context.Hotele.FindAsync(id);
            if (hotel == null)
            {
                return NotFound();
            }

            hotel.Pokoje = await _context.Pokoj.Where(p => p.HotelId == id).ToListAsync();
            hotel.Opinie = await _context.Opinia.Where(o => o.HotelId == id).ToListAsync();

            return View(hotel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PotwierdzUsuniecieHoteluPotwierdzenie(int id)
        {
            var hotel = await _context.Hotele.FindAsync(id);
            if (hotel == null)
            {
                return NotFound();
            }

            var pokoje = await _context.Pokoj.Where(p => p.HotelId == id).ToListAsync();
            var opinie = await _context.Opinia.Where(o => o.HotelId == id).ToListAsync();

            _context.Pokoj.RemoveRange(pokoje);
            _context.Opinia.RemoveRange(opinie);

            _context.Hotele.Remove(hotel);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool HotelExists(int id)
        {
            return _context.Hotele.Any(e => e.Id == id);
        }

        public async Task<IActionResult> WyswietlPokoje(int hotelId)
        {
            var pokoje = await _context.Pokoj
                .Where(p => p.HotelId == hotelId)
                .Include(p => p.Hotel)
                .ToListAsync();
            ViewBag.HotelId = hotelId;
            return View(pokoje);
        }

        [HttpPost]
        public async Task<IActionResult> DodajPokoj(DodajPokojViewModel nowyPokoj)
        {

            // Tutaj możesz dodać logikę sprawdzającą unikalność numeru pokoju, etc.
            var pokoj = new Pokoj
            {
                Nazwa = nowyPokoj.Nazwa,
                TypPokoju = nowyPokoj.TypPokoju,
                NumerPokoju = nowyPokoj.NumerPokoju,
                LiczbaOsob = nowyPokoj.LiczbaOsob,
                Cena = nowyPokoj.Cena,
                HotelId = nowyPokoj.HotelId,
            };

            _context.Pokoj.Add(pokoj);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(WyswietlPokoje), new { hotelId = nowyPokoj.HotelId });

            // Jeśli ModelState.IsValid nie jest spełniony, wróć do widoku z błędami
        }

        // Usuwanie pokoju - GET
        public async Task<IActionResult> UsunPokoj(int? pokojId)
        {
            if (pokojId == null)
            {
                return NotFound();
            }

            var pokoj = await _context.Pokoj.FindAsync(pokojId);

            if (pokoj == null)
            {
                return NotFound();
            }

            return View(pokoj);
        }

        // Usuwanie pokoju - POST
        [HttpPost]
        public async Task<IActionResult> PotwierdzUsunieciePokoj(int pokojId)
        {
            var pokoj = await _context.Pokoj.FindAsync(pokojId);

            if (pokoj == null)
            {
                return NotFound();
            }

            _context.Pokoj.Remove(pokoj);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(WyswietlPokoje), new { hotelId = pokoj.HotelId });
        }


        // Edytowanie istniejącego pokoju - GET
        public async Task<IActionResult> EdytujPokoj(int? pokojId)
        {
            if (pokojId == null)
            {
                return NotFound();
            }

            var pokoj = await _context.Pokoj
                .Include(p => p.Hotel) // Dodaj Include, aby pobrać obiekt Hotel wraz z pokojem
                .FirstOrDefaultAsync(p => p.Id == pokojId);

            if (pokoj == null)
            {
                return NotFound();
            }

            // Teraz masz dostęp do obiektu Hotel bezpośrednio z obiektu Pokoj
            var hotelId = pokoj.HotelId;

            return View(pokoj);
        }

        // Edytowanie istniejącego pokoju - POST
        [HttpPost]
        public async Task<IActionResult> EdytujPokoj(Pokoj pokoj)
        {
            try
            {
                _context.Entry(pokoj).State = EntityState.Modified;
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return NotFound();
            }
            // Po zaktualizowaniu pokoju, przenieś użytkownika do listy pokoi danego hotelu
            return RedirectToAction("WyswietlPokoje", new { hotelId = pokoj.HotelId });
        }

    }
}

BazyDanychProjekt/Controllers/HoteleController.cs
using Microsoft.AspNetCore.Mvc;
using BazyDanychProjekt.Models;
using System.Collections.Generic;
using BazyDanychProjekt.Services;
using Microsoft.AspNetCore.Authorization;

namespace BazyDanychProjekt.Controllers
{
    [Authorize]
    public class HoteleController : Controller
    {
        private readonly IHoteleService _hoteleService;

        public HoteleController(IHoteleService hoteleService)
        {
            _hoteleService = hoteleService;
        }

        public IActionResult Index()
        {
            List<Hotel> hotele = _hoteleService.PobierzHotele();

            return View(hotele);
        }

        public IActionResult Szczegoly(int id)
        {
            Hotel hotel = _hoteleService.PobierzHotel(id);

            if (TempData.ContainsKey("BladRezerwacji"))
            {
                ViewBag.BladRezerwacji = TempData["BladRezerwacji"];
            }
            if (TempData.ContainsKey("PomyslnaRezerwacja"))
            {
                ViewBag.PomyslnaRezerwacja = TempData["PomyslnaRezerwacja"];
            }

            if (hotel == null)
            {
                return RedirectToAction("Blad", "Home");
            }

            return View(hotel);
        }
    }
}

BazyDanychProjekt/Controllers/RezerwacjeController.cs
using BazyDanychProjekt.Data;
using BazyDanychProjekt.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BazyDanychProjekt.Controllers
{
    [Authorize]
    public class RezerwacjeController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<Uzytkownik> _userManager;

        public RezerwacjeController(ApplicationDbContext context, UserManager<Uzytkownik> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [HttpPost]
        public async Task<IActionResult> DodajRezerwacje(RezerwacjeViewModel model)
        {
                bool czyPokojDostepny = await SprawdzDostepnoscPokoju(model.PokojId, model.DataPoczatek, model.DataKoniec);

                if (czyPokojDostepny)
                {
                    var rezerwacja = new Rezerwacja
                    {
                        PokojId = model.PokojId,
                        UzytkownikId = HttpContext.Session.GetString("UserId"),
                        DataPoczatek = model.DataPoczatek,
                        DataKoniec = model.DataKoniec
                    };
                    
                    _context.Rezerwacja.Add(rezerwacja);
                    await _context.SaveChangesAsync();
                    TempData["PomyslnaRezerwacja"] = "Pomyślnie dokonano rezerwacji";
                    return RedirectToAction("Szczegoly", "Hotele", new { id = model.HotelId });
                }
                else
                {
                    TempData["BladRezerwacji"] = "Termin jest zajęty. Wybierz inny okres.";
                    return RedirectToAction("Szczegoly", "Hotele", new { id = model.HotelId });
                }
        }

        public async Task<IActionResult> MojeRezerwacje()
        {
            var mojeRezerwacje = await _context.Rezerwacja
                .Include(r => r.Pokoj)
                    .ThenInclude(p => p.Hotel)
                .Where(r => r.UzytkownikId == HttpContext.Session.GetString("UserId"))
                .ToListAsync();

            return View(mojeRezerwacje);
        }

        private async Task<bool> SprawdzDostepnoscPokoju(int pokojId, DateTime dataRozpoczecia, DateTime dataZakonczenia)
        {
            var zajeteTerminy = await _context.Rezerwacja
                .Where(r => r.PokojId == pokojId)
                .Where(r => (dataRozpoczecia >= r.DataPoczatek && dataRozpoczecia <= r.DataKoniec) ||
                            (dataZakonczenia >= r.DataPoczatek && dataZakonczenia <= r.DataKoniec))
                .ToListAsync();

            return zajeteTerminy.Count == 0;
        }
    }
}

BazyDanychProjekt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BazyDanychProjekt</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BazyDanychProjekt.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Hotele" asp-action="Index">Lista Hoteli</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Rezerwacje" asp-action="MojeRezerwacje">Moje Rezerwacje</a>
                            </li>

                            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="AdminPanel" asp-action="Index">Panel Administracyjny</a>
                                </li>
                            }

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Konto" asp-action="Wyloguj">Wyloguj</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BazyDanychProjekt - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
</body>
</html>